name = "grad_meh"
prefix = "grad_meh"
author = "Gruppe Adler"
folder_optionals = false
files = [
    "mod.cpp",
    "Adler.paa",
    "LICENSE",
    "README.md",
    "*.dll",
    "*.pdb"
]
key_name = "{{prefix}}-{{version}}"
sig_name = "{{prefix}}-{{version}}"