name: 'Add to Release'

on: [release]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@master
      name: 'Checkout  the source code from GitHub'

    - uses: ./.github/actions/update-versionfile
      name: 'Update script_version.hpp'

    - uses: gruppe-adler/action-release-with-hemtt@1.0
      name: 'Build Mod with HEMTT'
      id: build

    - uses: Shopify/upload-to-release@1.0.0
      name: 'Add to release'
      with:
        name: '${{ steps.build.outputs.zip_name }}.zip'
        path: ${{ steps.build.outputs.zip_path }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        content-type: application/zip