name: '[CI] Build Mod'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: 'Checkout source code'
      uses: actions/checkout@master
    - name: 'Build Mod with HEMTT'
      uses: gruppe-adler/action-release-with-hemtt@1.0
      id: build
    - name: 'Upload artifact'
      uses: actions/upload-artifact@master
      with:
        name: 'packed-mod'
        path: ${{ steps.build.outputs.zip_path }}
